### PR TITLE
Remove the submodules

### PR DESCRIPTION
**Pull request by danholdaway**
It can be problematic to have JCB use submodules explicitly and since they are really only used for testing they are removed. In their place is a custom checkout script that performs the exact same work as the git submodules but has to be run manually, as reflected in the README.

Users adding testing of a client simply register it in a YAML file, similar to how a `.gitmodules` file would look.

Depends:
- https://github.com/NOAA-EMC/jcb-gdas/pull/16

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@danholdaway looks like we need some `pip` magic in the github action first

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Where and how do the changes in this PR tie into GDASApp and g-w?

**Comment by danholdaway** [comment]
@RussTreadon-NOAA I will work on the GDASapp and GW workflows next.

**Comment by RussTreadon-NOAA** [comment]
GDASApp PR [#11146](https://github.com/NOAA-EMC/GDASApp/pull/1146) has been merged.  Do likewise for this PR.

**Pull request merged**
